services:
  grader:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    container_name: coduck-grader
    entrypoint: [ "sleep", "infinity" ]
    restart: unless-stopped
    volumes:
      - ./shared:/shared
